### ISSUE TITLE
Broker closes connection if keep_alive is 1 second

### ISSUE THREAD

**Issue by kivaari** [kivaari/MQTT.jl#2]
Mosquitto responds to the first pingreq packet with a pingresp but then just closes the socket. This also happens on localhost and if pingreq packets get sent more often than one second manually.

**Comment by AlexanderRohde** [comment]
Because we start sending pings **after** receiving the CONNACK the first ping probably arrives to late.

> Clients are allowed to send further Control Packets immediately after sending a CONNECT Packet; Clients need not wait for a CONNACK Packet to arrive from the Server.

We could start sending pings immateriality to accommodate lower keep alive values.
But if the client/server or network are to slow you still will be disconnected.
I could not get keep_alive=1 to work using test.mosquitto.org but broker.mqttdashboard.com didn't disconnect me.

**Comment by kivaari** [comment]
Yeah this seems like a mosquitto problem. I don't think the network could be too slow. Even when I connect to mosquitto over localhost AND start sending pingreqs immediately after the connect packet it still disconnects.  But it's confusing that it still responds to packets before the disconnect. Even if you spam packets he responds to all of them and then disconnects.

Might be interesting to see if this also happens with other SDKs and is actually a bug in mosquitto itself.
